[deprecation]
showPyplotGlobalUse = "False"

[theme]
# Primary accent color for interactive elements.
primaryColor = "#0083B8"

# Background color for the main content area.
backgroundColor = "#fff0f5"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ffffff"

# Color used for almost all text.
textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "serif"
